name: Exportar dados do WakaTime
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Configurar Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 16
      - name: Instalar dependências
        run: npm ci
      - name: Exportar dados do WakaTime
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          WAKATIME_USER: ${{ secrets.WAKATIME_USER }}
        run: npx wakatime-to-json
