name: Exportar dados do WakaTime
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 16
      - name: Instalar dependências
        run: npm ci
      - name: Exportar dados do WakaTime
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          WAKATIME_USER: ${{ secrets.WAKATIME_USER }}
        run: npx wakatime-to-json
      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add wakatime-data.json
          git commit -m "Update wakatime-data.json"
          git push origin HEAD
