name: Exportar dados do WakaTime
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 16
      - name: Instalar dependências
        run: npm ci
      - name: Exportar dados do WakaTime
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          WAKATIME_USER: ${{ secrets.WAKATIME_USER }}
        run: npx wakatime-to-json
      - name: Verificar mudanças, commit e push dos dados exportados
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if git status --porcelain | grep -q "wakatime-data.json"; then
            echo "Houve modificações no arquivo wakatime-data.json"
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add wakatime-data.json
            git commit -m "Adicionar dados exportados do WakaTime"
            git push --set-upstream origin ${{ github.ref }}
          else
            echo "Não houve modificações no arquivo wakatime-data.json"
          fi
